# Generated by Django 4.0.4 on 2022-04-19 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera_id', models.IntegerField()),
                ('city', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Crashed_frames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crash_time', models.DateTimeField(auto_created=True)),
                ('frame_id', models.IntegerField()),
                ('camera_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.camera_info')),
            ],
        ),
    ]
