# Generated by Django 4.0.4 on 2022-04-20 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crashed_frames',
            name='img',
            field=models.ImageField(default='-', upload_to='pics'),
        ),
    ]
